In [1]:
import numpy as np

In [2]:
# 1D Array
a = np.array([1, 2, 3])
print("1D Array:", a)

# 2D Array
b = np.array([[1, 2], [3, 4]])
print("2D Array:\n", b)


1D Array: [1 2 3]
2D Array:
 [[1 2]
 [3 4]]


In [ ]:
print("Shape of b:", b.shape)
print("Dimensions:", b.ndim)
print("Data Type:", b.dtype)
print("Size (total elements):", b.size)

In [3]:
a = np.array([10, 20, 30])
b = np.array([1, 2, 3])

# Element-wise addition
print("Addition:", a + b)

# Subtraction, Multiplication, Division
print("Multiplication:", a * b)
print("Division:", a / b)


Addition: [11 22 33]
Multiplication: [10 40 90]
Division: [10. 10. 10.]


In [4]:
print("Zeros:\n", np.zeros((2, 3)))
print("Ones:\n", np.ones((3, 3)))
print("Arange:\n", np.arange(0, 10, 2))
print("Linspace:\n", np.linspace(0, 1, 5))


Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]
Ones:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Arange:
 [0 2 4 6 8]
Linspace:
 [0.   0.25 0.5  0.75 1.  ]


In [5]:
arr = np.arange(1, 10)
reshaped = arr.reshape(3, 3)
print("Reshaped 3x3:\n", reshaped)

# Indexing
print("Element at [1,2]:", reshaped[1, 2])
print("First row:", reshaped[0])


Reshaped 3x3:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Element at [1,2]: 6
First row: [1 2 3]


In [6]:
print("Sum:", reshaped.sum())
print("Mean:", reshaped.mean())
print("Standard Deviation:", reshaped.std())

Sum: 45
Mean: 5.0
Standard Deviation: 2.581988897471611


In [7]:
print("Greater than 5:\n", reshaped > 5)
print("Filtered Values > 5:\n", reshaped[reshaped > 5])

Greater than 5:
 [[False False False]
 [False False  True]
 [ True  True  True]]
Filtered Values > 5:
 [6 7 8 9]


In [8]:
matrix = np.array([[1, 2], [3, 4]])
vector = np.array([1, 0])

print("Broadcasted Addition:\n", matrix + vector)

Broadcasted Addition:
 [[2 2]
 [4 4]]
